### ISSUE TITLE
shell: UnboundLocalError when save to png/bmp/jpg

### ISSUE THREAD

**Issue by pthr** [enthought/chaco#133]
In shell/commands.py, save mehod. A PdfPlotGraphicsContext instance is used to save to pdf, and the same object is used in the code to save to png/bmp/jpg (can be used to save to png/bmp/jpg at all?), however in that case the instance is not created because that's done in if ext == ".pdf". Therefore a  save('chacoplot.png') will result in a UnboundLocalError: local variable 'gc' referenced before assignment.

**Comment by WarrenWeckesser** [comment]
Looks like this was fixed by https://github.com/enthought/chaco/pull/149

**Comment by aaronayres35** [comment]
closing as chaco.shell was removed in #667
