### ISSUE TITLE
Documentation needs updates

### ISSUE THREAD

**Issue by timdiller** [enthought/chaco#161]
- [ ] [Introduction](http://docs.enthought.com/chaco/user_manual/introduction.html) is incomplete
- [ ] [Tools and overlay section](http://docs.enthought.com/chaco/user_manual/tools.html) is stubs-only
- [ ] [Common Usages](http://docs.enthought.com/chaco/user_manual/common_patterns.html) is stubs-only
- [ ] [Webinar links](http://docs.enthought.com/chaco/user_manual/tutorials_and_examples.html#webinars) are broken/out of date
- [ ] The documentation needs review to be sure the API and models are up to date.

**Comment by rahulporuri** [comment]
closing in favor of #587
