### ISSUE TITLE
TypeError on import of chaco.chaco_plot_editor

### ISSUE THREAD

**Issue by SavinaRoja** [enthought/chaco#182]
```
>>> import chaco.chaco_plot_editor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pablo/Desktop/chaco-4.4.1/chaco/chaco_plot_editor.py", line 52, in <module>
    color_editor = RGBAColorEditor()
TypeError: 'NoneType' object is not callable
```

Python version is 2.7.3
Chaco version is 4.4.1
Enable version is 4.3.0
GCC version is 4.6.3

Was trying to import ChacoPlotItem in a new build of 4.4.1 (was working with 4.0.0 in Ubuntu repository).

**Comment by bufalolento97** [comment]
Hi!
I'm having the same issue... How did you solve it?

**Comment by rahulporuri** [comment]
This issue can happen if no toolkit is installed into the python environment. The solution is to install a supported toolkit e.g. pyqt5, pyqt4, wxpython into the python env. If that doesn't solve the issue fully, you will need to manually set the `ETS_TOOLKIT` environment variable appropriately e.g. `ETS_TOOLKIT=qt` if the toolkit is pyqt4/pyqt5 and `wx` if wxpython is installed.

With that, im closing this issue. Please reopen if that doesn't actually solve the issue or if a new issue comes up.

**Comment by rahulporuri** [comment]
ref https://github.com/enthought/enable/blob/5ce24ecf140cf090758881f0fccd5eac60e12026/enable/trait_defs/ui/rgba_color_editor.py#L12-L17
