### ISSUE TITLE
ArrayDataSource get_mask_data() fails when data is None

### ISSUE THREAD

**Issue by corranwebster** [enthought/chaco#245]
See this test here:

https://github.com/enthought/chaco/blob/enh/data-source-tests/chaco/tests/arraydatasource_test_case.py#L108

More generally, I think that the behaviour for an empty data source is probably wrong (why a _scalar_ `0.0` instead of `array([])`?) but I'm not sure what will break if that is changed.

**Comment by aaronayres35** [comment]
Updated link: https://github.com/enthought/chaco/blob/b74e14918ad533d973775d78feaf1b80bfa4095a/chaco/tests/test_arraydatasource.py#L102-L108 

Uncommenting the skip the test fails with:
```
======================================================================
ERROR: test_get_data_mask_no_data (chaco.tests.test_arraydatasource.ArrayDataSourceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aayres/Desktop/chaco/chaco/tests/test_arraydatasource.py", line 106, in test_get_data_mask_no_data
    data, mask = data_source.get_data_mask()
  File "/Users/aayres/Desktop/chaco/chaco/array_data_source.py", line 158, in get_data_mask
    return self._data, ones(len(self._data), dtype=bool)
TypeError: object of type 'NoneType' has no len()

----------------------------------------------------------------------
```
