### ISSUE TITLE
ArrayDataSource __getstate__ doesn't call super

### ISSUE THREAD

**Issue by corranwebster** [enthought/chaco#248]
It probably should, given that `AbstractDataSource.__getstate__` does things.

**Comment by rahulporuri** [comment]
note that #250 supercedes this issue and this issue can be closed if the serialization code is removed.

**Comment by corranwebster** [comment]
No, #250 does not supercede - `__getstate__` is standard Python stuff (https://docs.python.org/3/library/pickle.html#object.__getstate__) and there's additional Traits support for `__getstate__` IIRC.

**Comment by aaronayres35** [comment]
this was fixed in #633
