### ISSUE TITLE
Serializable mixin should be removed

### ISSUE THREAD

**Issue by corranwebster** [enthought/chaco#250]
The class is not used by any current code, appears to be broken, and the problem it was meant to solve (selection of which traits to pickle) is better solved via the use of `transient` traits metadata.

Technically this is a backwards-incompatible change, however.

**Comment by rahulporuri** [comment]
@corranwebster it's not clear to me what all code can be thrown out but can we throw out the persistence methods e.g. `__getstate__` along with `_post_init`.

**Comment by corranwebster** [comment]
I was referring to this class: https://github.com/enthought/chaco/blob/e3423614d654a203bd82ee087c085abe13b465b1/chaco/serializable.py and its tests.

**Comment by corranwebster** [comment]
Also `__getstate__` methods should not be thrown out - it is standard Python stuff: https://docs.python.org/3/library/pickle.html#object.__getstate__

We do ned to make sure it behaves nicely with Traits `__getstate__`: https://github.com/enthought/traits/blob/5f2effc0254570dfa7736d8bf53eb224c9877c57/traits/has_traits.py#L1267
