### ISSUE TITLE
Remove chaco.datamapper and subdivision code

### ISSUE THREAD

**Issue by corranwebster** [enthought/chaco#253]
These modules, although they contain some algorithmic content, are holdovers from Chaco 1.  They are not used by any current code, are completely untested, and opaque regarding their use.  There may be value to them, but that value is gone as far as institutional memory is concerned.

Removing them would be technically not backward compatible, but likely not problematic.

**Comment by rahulporuri** [comment]
just confirming that this involves the following three modules, removed in #577 

- `chaco.datamapper`
- `chaco.subdivision_cells`
- `chaco.subdivision_mapper`
