### ISSUE TITLE
Is it possible to plot from hdf5 file?

### ISSUE THREAD

**Issue by Losiara** [enthought/chaco#283]
Not sure is a proper place to ask such question. But couldn't find info anywhere else. I need to plot it like this:
```python
import pyplot as p
f = h5py.File("November_Run3.hdf5",'r')
# Retrieve HDF5 dataset
first_detector = f['/0/first_detector']
# Make a properly scaled time axis
x_axis = np.arange(len(first_detector))*first_detector.attrs['dt']
# Plot the result
p.plot(x_axis, first_detector[...])
```

**Comment by jonathanrocher** [comment]
@Losiara Yes, it is possible to plot data from an HDF5 file in Chaco, very similarly to what you have done with matplotlib. As a reminder, if you want a static plot, what you have with matplotlib is the easiest way to go. As explained in its doc (http://docs.enthought.com/chaco/index.html), Chaco allows for custom,  complex, connected and/or interactive plotting typically inside a GUI application. But that requires more coding, including being comfortable with object oriented programming with Traits . If that's what you need, to do something similar to what you have above, I would follow the example in http://docs.enthought.com/traits/traits_user_manual/index.html except that the `__init__` method would receive numpy arrays from your HDF5 file as `x` and `y` as opposed to trivial `linspace`s. 

Does that help?

**Comment by Losiara** [comment]
Yes, thank you!
