### ISSUE TITLE
Displaying large data sets with Chaco

### ISSUE THREAD

**Issue by sidneybennett** [enthought/chaco#303]
I am having trouble displaying large data sets with Chaco. I have reproduced the problem by modifying the bigdata.py example. I changed the y data from the bessel function to just random data. Perhaps the first quarter of the data displays fine, but not the rest. Code and screen grab are attached. Matplotlib plots similar data just fine. I think this might be a problem or limitation with Chaco, but it's hard to be sure. Any ideas?

Windows 7 64bit, newly installed 1.7.4.3348 (64 bit).

Update: Response from Enthought confirms the issue, and suggests using a scatter plot for the time being.

![bitdata_problem](https://cloud.githubusercontent.com/assets/20974721/17597098/5b7ed7bc-5fc2-11e6-935b-282636bd02b5.png)

[bigdata.py.txt](https://github.com/enthought/chaco/files/413751/bigdata.py.txt)

**Comment by jdmarch** [comment]
Confirmed for data sets larger than approx 29K points.

**Comment by corranwebster** [comment]
Definitely something odd going on here.  If I use `y = jn(i, x)+np.random.rand(len(x))` I get the following: 
<img width="601" alt="screen shot 2016-08-12 at 10 10 44 am" src="https://cloud.githubusercontent.com/assets/600761/17618022/2ee67580-6075-11e6-8c9b-5a83c1b9a278.png">
Note the odd fill to the x-axis.

If I had to guess, this is most likely an issue with either Kiva's Image/Agg backend, or with Agg itself.  Matplotlib uses a slightly newer version of Agg, and a completely different way of binding to it, so differences are to be expected.

**Comment by jwiggins** [comment]
@corranwebster: Anybody from the Cambridge office going to be at EuroSciPy? I might have something related to this to discuss :wink:

**Comment by corranwebster** [comment]
@jwiggins I was hoping to be able to go, but can't make it this year.  Care to ping me (by e-mail, if needed) to discuss further?

**Comment by corranwebster** [comment]
@sidneybennett If you are able to check out the current master of Chaco and set `use_downsampling` to `True` then the changes in #317 appear to fix your problem (and should be much faster) thanks to new downsampling code.

The issue still persists when not downsampling, so I will leave this issue open.

**Comment by sidneybennett** [comment]
Corran Webster,
How do I "check out the current master of Chaco".  All I typically deal
with is the Enthought package manager.  Are you referring to checking out
from a GIT repository for Chaco?
Sid.

**Comment by corranwebster** [comment]
@sidneybennett yes, I was suggesting cloning the git repository and installing.  If you've never done that before and/or don't have a C compiler installed for building Python extensions (which is not trivial on Windows), then don't worry. Hopefully there will be a new Chaco release before the end of the year available via Enthought's package manager and you can test then.

**Comment by corranwebster** [comment]
Closing this, as hopefully fixed in current release.
