### ISSUE TITLE
img_plot not displaying data

### ISSUE THREAD

**Issue by nagalloway** [enthought/chaco#308]
Running programs like /chaco/examples/demo/basic/image_plot.py results in either a plot being displayed with no image, or a seg fault. 

Other notes:
Fresh install of Ubuntu 16.04 using chaco and related packages managed by apt. 
Issue #273 addressed a similar bug, which was found to relate to a bug in Enable. That bug had been solved and put into version 4.5.1-2, and the version I'm testing with is 4.5.1-2ubuntu1.

**Comment by corranwebster** [comment]
Thanks for the report.

Possibly related to #295? At root this is likely an Enable bug rather than a Chaco bug.

**Comment by rahulporuri** [comment]
closing as all of the `image_*.py` examples in `examples/demo/basic` work as expected at the moment on windows.
