### ISSUE TITLE
Don't put Cythonized .c files in source control, but do ship in sdist

### ISSUE THREAD

**Issue by corranwebster** [enthought/chaco#333]
Currently we check-in .c files produced by Cython to the source tree alongside the .pyx files so that people building the source don't need to have Cython installed.  This is awkward from the developer's perspective, however, and can result in noisy deltas.

Following discussion in #325 the the proposal is that we will only check in the .pyx files into source control, but we will ship the .c files as part of the sdist source distributions.  This change will mean that people wishing to work from non-released versions will need to have Cython installed (as will the CI environment), but people wanting to build a release from source won't need it.  Having Cython available is not as unreasonable a requirement as it was several years ago.

**Comment by itziakos** [comment]
> c files as part of the sdist source distributions.

to clarify, I think we should ship `only the c files`  in the source distribution not the `pyx`

**Comment by rkern** [comment]
I think we should ship the `.pyx` files as well and make sure they go into the installed package. Cython adds the appropriate line information to tracebacks, so we can see the code involved in the traceback if the `.pyx` files are installed.
