### ISSUE TITLE
Docs : Location of examples in Canopy is outdated

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#353]
See : http://docs.enthought.com/chaco/quickstart.html#location
Since Canopy 2.x, the Canopy installation path has changed so they need to be updated to reflect Canopy >2 and <2 path.

**Comment by corranwebster** [comment]
Possibly should just drop the Canopy < 2 and give EDM based instructions.

**Comment by rahulporuri** [comment]
edm based instructions for installing chaco?

**Comment by achabotl** [comment]
Closed by https://github.com/enthought/chaco/pull/462.
