### ISSUE TITLE
Building pyside egg fails (Travis CI)

### ISSUE THREAD

**Issue by jvkersch** [enthought/chaco#361]
The Pyside2 and shiboken2 repositories are gone (https://github.com/pyside/pyside2) but we still rely on them to build a pyside egg.

This came up in https://github.com/enthought/chaco/pull/360

**Comment by corranwebster** [comment]
There is a similar problem in Enable.  The fix is to switch to an EDM-based travis/appveyor script - TraitsUI has the current template for doing this.

**Comment by jvkersch** [comment]
Fixed in #365
