### ISSUE TITLE
ValueError after creating MultiArrayDataSource with latest numpy

### ISSUE THREAD

**Issue by RyanYoung25** [enthought/chaco#370]
**Problem Description**
When using chaco4.6.1 and numpy 1.13.1 a ValueError exception occurs one operation (or more) after creating a MultiArrayDataSource object passing in a numpy array.

After the exception is thrown everything works as intended, the exception shouldn't be thrown though. 

**Reproduction Steps:**

Install chaco 4.6.1 and numpy 1.13.1
In a python interpreter: 
```python
import numpy as np
from chaco.api import MultiArrayDataSource 

a = np.array([[1,2,3],[4,5,6]])
b = MultiArrayDataSource(a)  # The object is created fine without error
# Enter another line or try to print a
print(a)
#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Expected behavior:**

That exception shouldn't be thrown, especially not after the object was created

**OS, Python version:** 
This bug was encountered running: 
- Ubuntu 16.04 
- Python 2.7.12

**Comment by jvkersch** [comment]
I can reproduce locally. @RyanYoung25 Thanks for the bug report and the minimal working example, this is quite helpful.

**Comment by jvkersch** [comment]
Here's an example that reduces the bug down to Traits:
```python
from numpy import array, empty

from traits.api import HasStrictTraits, Trait, CArray

NumericalSequenceTrait = Trait(None, None, CArray(value=empty(0)))


class MultiArrayDataSource(HasStrictTraits):

    _data = NumericalSequenceTrait


if __name__ == '__main__':
    a = array([[1, 2, 3], [4, 5, 6]])
    b = MultiArrayDataSource(_data=a)
    print(a)

```

**Comment by mdickinson** [comment]
@jvkersch and I tracked this down this morning, and opened enthought/traits#376. A proposed fix is in enthought/traits#377.

**Comment by RyanYoung25** [comment]
Thanks for taking care of this so quickly!

**Comment by jvkersch** [comment]
@RyanYoung25 Thanks again for reporting! The fix is in Traits master, so depending on your environment you could either work off Traits master for now, or downgrade to numpy <= 1.12. I'll close this issue for now, but feel free to re-open or create additional issues if anything else crops up.
