### ISSUE TITLE
c_map_image and image_inspector examples broken with Python 3

### ISSUE THREAD

**Issue by yves-surrel** [enthought/chaco#371]
These two examples only display a white area.

Windows 7, python 3.5.2, chaco 4.6.1-2, Canopy 2.1.3.2542

**Comment by rahulporuri** [comment]
I'm not sure what "c_map_image" and "image_inspector" examples are specifically but I tested all of the `cmap_*.py` examples in `examples/demo/basic/` and the `image_inspector.py` script - and all of those examples worked as expected.
