### ISSUE TITLE
pip install from PyPI fails if NumPy not already installed

### ISSUE THREAD

**Issue by mdickinson** [enthought/chaco#372]
Chaco depends on NumPy, but doesn't declare that dependency in its setup.py.

**Comment by corranwebster** [comment]
But Chaco does depend on Enable, which does declare a dependency on Numpy, so you shouldn't every be in a situation where you don't have Numpy?

**Comment by rkern** [comment]
Note that the `setup.py` uses `numpy`, so adding it there won't accomplish anything except alleviating some OCD. If the goal is to get `pip` to work, you'll need a sidecar `requirements.txt` listing `numpy`.

**Comment by mdickinson** [comment]
> If the goal is to get pip to work

Sorry, yes, that was indeed the goal. Right now, `pip install chaco` to install from PyPI fails if NumPy isn't already installed. I should retitle this issue.

I'd argue that `numpy` should be added to the `setup.py` anyway as a runtime dependency, so that if one day we manage to produce wheels for Chaco then `pip` will be able to resolve dependencies properly.

**Comment by mdickinson** [comment]
> But Chaco does depend on Enable, which does declare a dependency on Numpy, so you shouldn't every be in a situation where you don't have Numpy?

Hmm, true. I guess the need to add NumPy to the runtime requirements really is at OCD level, then. :-)

And at that level, I'd say that the general rule is that any package that Chaco imports directly from should be in the requirements.
