### ISSUE TITLE
numpy.ndarray vs array

### ISSUE THREAD

**Issue by VenturaFranklin** [enthought/chaco#375]
Running the simple_line.py file in the examples\demo I get the error:

> traits.trait_errors.TraitError: The '_data' trait of an ArrayDataSource instance must be an array or None, but a value of array([ -5.00000000e+00,  -4.80000000e+00,  -4.60000000e+00,
>         -4.40000000e+00,  -4.20000000e+00,  -4.00000000e+00,
>         -3.80000000e+00,  -3.60000000e+00,  -3.40000000e+00,
>         -3.20000000e+00,  -3.00000000e+00,  -2.80000000e+00,
>         -2.60000000e+00,  -2.40000000e+00,  -2.20000000e+00,
>         -2.00000000e+00,  -1.80000000e+00,  -1.60000000e+00,
>         -1.40000000e+00,  -1.20000000e+00,  -1.00000000e+00,
>         -8.00000000e-01,  -6.00000000e-01,  -4.00000000e-01,
>         -2.00000000e-01,   4.44089210e-15,   2.00000000e-01,
>          4.00000000e-01,   6.00000000e-01,   8.00000000e-01,
>          1.00000000e+00,   1.20000000e+00,   1.40000000e+00,
>          1.60000000e+00,   1.80000000e+00,   2.00000000e+00,
>          2.20000000e+00,   2.40000000e+00,   2.60000000e+00,
>          2.80000000e+00,   3.00000000e+00,   3.20000000e+00,
>          3.40000000e+00,   3.60000000e+00,   3.80000000e+00,
>          4.00000000e+00,   4.20000000e+00,   4.40000000e+00,
>          4.60000000e+00,   4.80000000e+00,   5.00000000e+00,
>          5.20000000e+00,   5.40000000e+00,   5.60000000e+00,
>          5.80000000e+00,   6.00000000e+00,   6.20000000e+00,
>          6.40000000e+00,   6.60000000e+00,   6.80000000e+00,
>          7.00000000e+00,   7.20000000e+00,   7.40000000e+00,
>          7.60000000e+00,   7.80000000e+00,   8.00000000e+00,
>          8.20000000e+00,   8.40000000e+00,   8.60000000e+00,
>          8.80000000e+00,   9.00000000e+00,   9.20000000e+00,
>          9.40000000e+00,   9.60000000e+00,   9.80000000e+00,
>          1.00000000e+01,   1.02000000e+01,   1.04000000e+01,
>          1.06000000e+01,   1.08000000e+01,   1.10000000e+01,
>          1.12000000e+01,   1.14000000e+01,   1.16000000e+01,
>          1.18000000e+01,   1.20000000e+01,   1.22000000e+01,
>          1.24000000e+01,   1.26000000e+01,   1.28000000e+01,
>          1.30000000e+01,   1.32000000e+01,   1.34000000e+01,
>          1.36000000e+01,   1.38000000e+01,   1.40000000e+01,
>          1.42000000e+01,   1.44000000e+01,   1.46000000e+01,
>          1.48000000e+01,   1.50000000e+01]) <class 'numpy.ndarray'> was specified.

I am using Python 3.6 win32 and packages/versions in a virtualenv:
chaco==4.6.1
enable==4.6.2
numpy==1.13.1+mkl
pyface==5.1.0
PyQt4==4.11.4
scipy==0.19.1
traits==4.6.0
traitsui==5.1.0

Any thoughts on what I'm doing wrong or how to fix?

Thanks for your help,
Frank V.

**Comment by VenturaFranklin** [comment]
I set a breakpoint on line 177 of the validate function in the traits/trait_numeric file to see what is going on. The breakpoint seems to affect the behaviour.

However, if I comment out this line, it then looks as if the self._data is never set in Chaco's ArrayDataSource class. Which makes sense if the validation is failing.
I then return the value and then everything works fine. 

So somewhere in the try/except of the validate function is failing.

Here is what I've changed in the validate function and the result:
```
def validate ( self, object, name, value ):
    """ Validates that the value is a valid array.
    """
    try:
        # Make sure the value is an array:
        print("VALIDATE")
        type_value = type( value )
        if not isinstance( value, ndarray ):
            if not isinstance( value, SequenceTypes ):
                self.error( object, name, value )
            if self.dtype is not None:
                value = asarray( value, self.dtype )
            else:
                value = asarray( value )
        # Make sure the array is of the right type:
        if ((self.dtype is not None) and
            (value.dtype != self.dtype)):
            if self.coerce:
                value = value.astype( self.dtype )
            else:
                # XXX: this also coerces.
                value = asarray( value, self.dtype )
        # If no shape requirements, then return the value:
        trait_shape = self.shape
        if trait_shape is None:
            print('RETURNING?')
            return value
        # Else make sure that the value's shape is compatible:
        value_shape = value.shape
        if len( trait_shape ) == len( value_shape ):
            for i, dim in enumerate( value_shape ):
                item = trait_shape[i]
                if item is not None:
                    if type( item ) is int:
                        if dim != item:
                            break
                    elif ((dim < item[0]) or
                          ((item[1] is not None) and (dim > item[1]))):
                        break
            else:
                return value
    except Exception as inst:
        print(type(inst))    # the exception instance
        print(inst.args)     # arguments stored in .args
        print(inst)
    print(self.shape)
    print('THIS IS THE VALUE', value)
#         self.error( object, name, value )
    return value
```

> VALIDATE
> <class 'SystemError'>
> ('<built-in method write of _io.TextIOWrapper object at 0x001DB4B0> returned a result with an error set',)
> <built-in method write of _io.TextIOWrapper object at 0x001DB4B0> returned a result with an error set
> None
> THIS IS THE VALUE [ -5.00000000e+00  -4.80000000e+00  -4.60000000e+00  -4.40000000e+00
>   -4.20000000e+00  -4.00000000e+00  -3.80000000e+00  -3.60000000e+00
>   -3.40000000e+00  -3.20000000e+00  -3.00000000e+00  -2.80000000e+00
>   -2.60000000e+00  -2.40000000e+00  -2.20000000e+00  -2.00000000e+00
>   -1.80000000e+00  -1.60000000e+00  -1.40000000e+00  -1.20000000e+00
>   -1.00000000e+00  -8.00000000e-01  -6.00000000e-01  -4.00000000e-01
>   -2.00000000e-01   4.44089210e-15   2.00000000e-01   4.00000000e-01
>    6.00000000e-01   8.00000000e-01   1.00000000e+00   1.20000000e+00
>    1.40000000e+00   1.60000000e+00   1.80000000e+00   2.00000000e+00
>    2.20000000e+00   2.40000000e+00   2.60000000e+00   2.80000000e+00
>    3.00000000e+00   3.20000000e+00   3.40000000e+00   3.60000000e+00
>    3.80000000e+00   4.00000000e+00   4.20000000e+00   4.40000000e+00
>    4.60000000e+00   4.80000000e+00   5.00000000e+00   5.20000000e+00
>    5.40000000e+00   5.60000000e+00   5.80000000e+00   6.00000000e+00
>    6.20000000e+00   6.40000000e+00   6.60000000e+00   6.80000000e+00
>    7.00000000e+00   7.20000000e+00   7.40000000e+00   7.60000000e+00
>    7.80000000e+00   8.00000000e+00   8.20000000e+00   8.40000000e+00
>    8.60000000e+00   8.80000000e+00   9.00000000e+00   9.20000000e+00
>    9.40000000e+00   9.60000000e+00   9.80000000e+00   1.00000000e+01
>    1.02000000e+01   1.04000000e+01   1.06000000e+01   1.08000000e+01
>    1.10000000e+01   1.12000000e+01   1.14000000e+01   1.16000000e+01
>    1.18000000e+01   1.20000000e+01   1.22000000e+01   1.24000000e+01
>    1.26000000e+01   1.28000000e+01   1.30000000e+01   1.32000000e+01
>    1.34000000e+01   1.36000000e+01   1.38000000e+01   1.40000000e+01
>    1.42000000e+01   1.44000000e+01   1.46000000e+01   1.48000000e+01
>    1.50000000e+01]

**Comment by VenturaFranklin** [comment]
I think that error was related to the print statement print("VALIDATE") if I remove that from the above code and rerun the new exception is below:
> <class 'SystemError'>
> ("<class 'type'> returned a result with an error set",)
> <class 'type'> returned a result with an error set
> None
> THIS IS THE VALUE [ -5.00000000e+00  -4.80000000e+00  -4.60000000e+00  -4.40000000e+00
>   -4.20000000e+00  -4.00000000e+00  -3.80000000e+00  -3.60000000e+00
>   -3.40000000e+00  -3.20000000e+00  -3.00000000e+00  -2.80000000e+00
>   -2.60000000e+00  -2.40000000e+00  -2.20000000e+00  -2.00000000e+00
>   -1.80000000e+00  -1.60000000e+00  -1.40000000e+00  -1.20000000e+00
>   -1.00000000e+00  -8.00000000e-01  -6.00000000e-01  -4.00000000e-01
>   -2.00000000e-01   4.44089210e-15   2.00000000e-01   4.00000000e-01
>    6.00000000e-01   8.00000000e-01   1.00000000e+00   1.20000000e+00
>    1.40000000e+00   1.60000000e+00   1.80000000e+00   2.00000000e+00
>    2.20000000e+00   2.40000000e+00   2.60000000e+00   2.80000000e+00
>    3.00000000e+00   3.20000000e+00   3.40000000e+00   3.60000000e+00
>    3.80000000e+00   4.00000000e+00   4.20000000e+00   4.40000000e+00
>    4.60000000e+00   4.80000000e+00   5.00000000e+00   5.20000000e+00
>    5.40000000e+00   5.60000000e+00   5.80000000e+00   6.00000000e+00
>    6.20000000e+00   6.40000000e+00   6.60000000e+00   6.80000000e+00
>    7.00000000e+00   7.20000000e+00   7.40000000e+00   7.60000000e+00
>    7.80000000e+00   8.00000000e+00   8.20000000e+00   8.40000000e+00
>    8.60000000e+00   8.80000000e+00   9.00000000e+00   9.20000000e+00
>    9.40000000e+00   9.60000000e+00   9.80000000e+00   1.00000000e+01
>    1.02000000e+01   1.04000000e+01   1.06000000e+01   1.08000000e+01
>    1.10000000e+01   1.12000000e+01   1.14000000e+01   1.16000000e+01
>    1.18000000e+01   1.20000000e+01   1.22000000e+01   1.24000000e+01
>    1.26000000e+01   1.28000000e+01   1.30000000e+01   1.32000000e+01
>    1.34000000e+01   1.36000000e+01   1.38000000e+01   1.40000000e+01
>    1.42000000e+01   1.44000000e+01   1.46000000e+01   1.48000000e+01
>    1.50000000e+01]

**Comment by VenturaFranklin** [comment]
Looks to be related to this:
https://bugs.python.org/issue23571

**Comment by VenturaFranklin** [comment]
This may be an issue with traits, I created a pull request there: https://github.com/enthought/traits/pull/381
Though it may be chaco not setting an attribute that the trait validation needs.

**Comment by rkern** [comment]
I'm guessing that the `type()` call isn't actually the source of the problem, as I expect the `print()` wasn't the origin of the false exception either. Neither `print()` nor `type()` ought not to be that buggy, much less both at the same time. :-)

It's just that the exception gets set by something where the new `issue23571` check doesn't happen for whatever reason, then `type()` is called, the `issue23571` check happens and we get a `SystemError` falsely blaming `type()`.

**Comment by rkern** [comment]
Can you try a plain `raise` in the exception handler? Maybe we can see something in the traceback.

**Comment by VenturaFranklin** [comment]
plain raise gets the same error from before, here is the full traceback:
`python simple_line.py`

> Traceback (most recent call last):
>   File "simple_line.py", line 150, in <module>
>     demo.configure_traits()
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traits\has_traits.py", line 2171, in configure_traits
>     kind, handler, id, scrollable, args )
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\toolkit.py", line 213, in view_application
>     id, scrollable, args )
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\view_application.py", line 83, in view_application
>     scrollable, args ).ui.result
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\view_application.py", line 134, in __init__
>     args       = self.args )
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\view.py", line 433, in ui
>     ui.ui( parent, kind )
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\ui.py", line 221, in ui
>     self.rebuild( self, parent )
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\toolkit.py", line 155, in ui_live
>     ui_live.ui_live( ui, parent )
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\ui_live.py", line 39, in ui_live
>     _ui_dialog(ui, parent, BaseDialog.NONMODAL)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\ui_live.py", line 59, in _ui_dialog
>     BaseDialog.display_ui(ui, parent, style)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\ui_base.py", line 482, in display_ui
>     ui.owner.init(ui, parent, style)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\ui_live.py", line 177, in init
>     self.add_contents(panel(ui), bbox)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\ui_panel.py", line 255, in panel
>     panel = _GroupPanel(content[0], ui).control
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\ui_panel.py", line 592, in __init__
>     layout = self._add_items(content, inner)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\qt4\ui_panel.py", line 852, in _add_items
>     ui, object, name, item.tooltip, None
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\editor_factory.py", line 145, in simple_editor
>     description = description )
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traitsui\editor.py", line 133, in __init__
>     self.old_value = getattr( self.object, self.name )
>   File "simple_line.py", line 143, in _plot_default
>     bgcolor="lightgray", use_backbuffer=True)
>   File "simple_line.py", line 45, in __init__
>     self._setup_plots()
>   File "simple_line.py", line 61, in _setup_plots
>     color=tuple(COLOR_PALETTE[i]))
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\chaco\plot_factory.py", line 58, in create_scatter_plot
>     index, value = _create_data_sources(data)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\chaco\plot_factory.py", line 29, in _create_data_sources
>     index = ArrayDataSource(array(index), sort_order=index_sort)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\chaco\array_data_source.py", line 110, in __init__
>     self.set_data(data, sort_order)
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\chaco\array_data_source.py", line 123, in set_data
>     self._data = newdata
>   File "C:\Users\venturf2\Envs\blade\lib\site-packages\traits\trait_handlers.py", line 172, in error
>     value )
> traits.trait_errors.TraitError: The '_data' trait of an ArrayDataSource instance must be an array or None, but a value of array([ -5.00000000e+00,  -4.80000000e+00,  -4.60000000e+00,
>         -4.40000000e+00,  -4.20000000e+00,  -4.00000000e+00,
>         -3.80000000e+00,  -3.60000000e+00,  -3.40000000e+00,
>         -3.20000000e+00,  -3.00000000e+00,  -2.80000000e+00,
>         -2.60000000e+00,  -2.40000000e+00,  -2.20000000e+00,
>         -2.00000000e+00,  -1.80000000e+00,  -1.60000000e+00,
>         -1.40000000e+00,  -1.20000000e+00,  -1.00000000e+00,
>         -8.00000000e-01,  -6.00000000e-01,  -4.00000000e-01,
>         -2.00000000e-01,   4.44089210e-15,   2.00000000e-01,
>          4.00000000e-01,   6.00000000e-01,   8.00000000e-01,
>          1.00000000e+00,   1.20000000e+00,   1.40000000e+00,
>          1.60000000e+00,   1.80000000e+00,   2.00000000e+00,
>          2.20000000e+00,   2.40000000e+00,   2.60000000e+00,
>          2.80000000e+00,   3.00000000e+00,   3.20000000e+00,
>          3.40000000e+00,   3.60000000e+00,   3.80000000e+00,
>          4.00000000e+00,   4.20000000e+00,   4.40000000e+00,
>          4.60000000e+00,   4.80000000e+00,   5.00000000e+00,
>          5.20000000e+00,   5.40000000e+00,   5.60000000e+00,
>          5.80000000e+00,   6.00000000e+00,   6.20000000e+00,
>          6.40000000e+00,   6.60000000e+00,   6.80000000e+00,
>          7.00000000e+00,   7.20000000e+00,   7.40000000e+00,
>          7.60000000e+00,   7.80000000e+00,   8.00000000e+00,
>          8.20000000e+00,   8.40000000e+00,   8.60000000e+00,
>          8.80000000e+00,   9.00000000e+00,   9.20000000e+00,
>          9.40000000e+00,   9.60000000e+00,   9.80000000e+00,
>          1.00000000e+01,   1.02000000e+01,   1.04000000e+01,
>          1.06000000e+01,   1.08000000e+01,   1.10000000e+01,
>          1.12000000e+01,   1.14000000e+01,   1.16000000e+01,
>          1.18000000e+01,   1.20000000e+01,   1.22000000e+01,
>          1.24000000e+01,   1.26000000e+01,   1.28000000e+01,
>          1.30000000e+01,   1.32000000e+01,   1.34000000e+01,
>          1.36000000e+01,   1.38000000e+01,   1.40000000e+01,
>          1.42000000e+01,   1.44000000e+01,   1.46000000e+01,
>          1.48000000e+01,   1.50000000e+01]) <class 'numpy.ndarray'> was specified.

**Comment by rkern** [comment]
Interesting! That `raise` is never triggered. It must be the earlier `.error()` call, then. Can you `print(ndarray)` before the first `.error()` call (hopefully not triggering `issue23571`)? Maybe the `global` statement from `ArrayBase.__init__()` isn't doing the right thing in Python 3.

**Comment by mdickinson** [comment]
@VenturaFranklin: Are you in a position to try with Traits master branch? It's possible (though I wouldn't go so far as probably) that enthought/traits#377 fixed this.

**Comment by rkern** [comment]
That looks likely.

**Comment by VenturaFranklin** [comment]
Yes, that worked! I cloned the master branch and then python setup.py install 
I have traits==4.7.0.dev59
And no longer see the issue.
Thanks for your help!
