### ISSUE TITLE
runnings tests on Win - Appveyor

### ISSUE THREAD

**Issue by ThomasLecocq** [enthought/chaco#377]
Do you guys have any objection to running win install tests on appveyor ?

https://github.com/enthought/chaco/issues/376 is an example that could maybe have been caught in win tests ? 

I can try to PR an appveyor.ylm recipe if you want.

**Comment by corranwebster** [comment]
Absolutely none - we have Appveyor tests for other ETS projects, we simply haven't gotten around to setting them up for Chaco.

**Comment by ThomasLecocq** [comment]
okay... I'll have a look at the other projects... I guess you'd want the test to run with edm like for travis ?

**Comment by corranwebster** [comment]
The reference for this is probably the TraitsUI setup, particularly the test runner (https://github.com/enthought/traitsui/blob/master/etstool.py) and the Appveyor setup there https://github.com/enthought/traitsui/blob/master/appveyor.yml

@itziakos wrote that code, and so may be able to give you some help if you get stuck.
