### ISSUE TITLE
Bug in the connected single range example 

### ISSUE THREAD

**Issue by yzaretskiy** [enthought/chaco#393]
**Problem Description**
[Connected single range](https://github.com/enthought/chaco/blob/master/examples/tutorials/scipy2008/connected_single_range.py) example has a bug - left-hand side plot has all its points collapse onto the y-axis.

![screenshot from 2017-12-18 12-30-29](https://user-images.githubusercontent.com/34460026/34121614-44e58854-e3ef-11e7-8eab-43c7b725b1b7.png)
**Reproduction Steps:**
Run the linked example from the newly installed `edm` environment. 

**OS, Python version:**
Ubuntu 16.04, Python 2.7, Chaco 4.7.1

**Comment by achabotl** [comment]
The demo worked in 4.6.1, Python 2 and 3 on macOS.

**Comment by yzaretskiy** [comment]
FWIW, it works on my Ubuntu 16.04 laptop when I revert to Chaco 4.6, but then I get the following warnings:

```
/home/yzaretskiy/.edm/envs/old-chaco/lib/python2.7/site-packages/chaco/array_data_source.py:123: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
/home/yzaretskiy/.edm/envs/old-chaco/lib/python2.7/site-packages/chaco/axis.py:498: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  for tickpos in mapped_tick_positions]))
/home/yzaretskiy/.edm/envs/old-chaco/lib/python2.7/site-packages/chaco/axis.py:499: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_list = tick_list
/home/yzaretskiy/.edm/envs/old-chaco/lib/python2.7/site-packages/chaco/axis.py:500: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_positions = self._tick_positions
/home/yzaretskiy/.edm/envs/old-chaco/lib/python2.7/site-packages/chaco/scatterplot.py:416: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._cached_selected_pts = points
```

**Comment by achabotl** [comment]
Those warnings were also reported in #251.

**Comment by rkern** [comment]
You can ignore the warnings. They were fixed by #350 which made it into the 4.7.0 release.

**Comment by cfarrow** [comment]
Note that the updated range is the one that gets messed up. In this case it's `scatterplot`. Swapping the assignment on [line 42](https://github.com/enthought/chaco/blob/master/examples/tutorials/scipy2008/connected_single_range.py#L42) results in the line plot getting messed up.

**Comment by rkern** [comment]
Found it: #394
