### ISSUE TITLE
Upgrade Cython version for Python 3.7 compatibility

### ISSUE THREAD

**Issue by sputnick1124** [enthought/chaco#426]
**Problem Description**

`pip install chaco` fails with complaints of missing fields on `PyThreadState` struct when using Python 3.7. This is because Python 3.7 has rearranged its exception information.

**Reproduction Steps:**

`pip install chaco` using Python 3.7

**Expected behavior:**

Successful install of chaco under Python 3.7

**OS, Python version:** 

Linux (CentOS 7)
Python 3.7.0

This has been addressed in cython upstream (issue: https://github.com/cython/cython/issues/1955, PR: https://github.com/cython/cython/pull/1956) and plagues a number of other projects (https://www.google.com/search?q=pythreadstate+has+no+member+named+exc_type) including [enable](https://github.com/enthought/enable) (https://github.com/enthought/enable/issues/316)

Regenerating the sources with a newer Cython fixes the issue (https://github.com/sputnick1124/chaco/commit/a57b3a9ccba6b05e75aa6bcfc0a16d4510e48ce7)

**Comment by silverjam** [comment]
This should be fixed by #433

**Comment by sputnick1124** [comment]
Great! Thanks!
