### ISSUE TITLE
PdfPlotGraphicsContext changes plot font

### ISSUE THREAD

**Issue by notmatthancock** [enthought/chaco#428]
**Problem Description**

When using the `PdfPlotGraphicsContext` to export to PDF, the `draw` function executed in the `render_component` function alters the plot font.

**Reproduction Steps:**

Code to reproduce issue:

```python
from traits.api import *
from traitsui.api import *
from chaco.api import *
from chaco.pdf_graphics_context import PdfPlotGraphicsContext
from enable.api import ComponentEditor


class PlotContainer(HasTraits):

    plot = Instance(Plot)
    save = Button

    def _plot_default(self):
        data = ArrayPlotData(x=[1, 2, 3, 4], y=[2, 3, 5, 8])
        p = Plot(data)
        p.plot(('x', 'y'))
        return p

    def _save_fired(self):

        # Do save stuff ...
        self.plot.do_layout(force=True)
        gc = PdfPlotGraphicsContext(filename='./plot.pdf')
        gc.render_component(self.plot)
        gc.save()

        print('plot saved!')

    traits_view = View(
        VGroup(
            UItem('plot', editor=ComponentEditor()),
            UItem('save'),
        )
    )


if __name__ == '__main__':
    pc = PlotContainer()
    pc.configure_traits()
```

**Expected behavior:**

Font should remain the same after focus is brought back to window, but it does not.

**OS, Python version:**
Occurs on both Ubuntu 18 and windows 7

```
$ python -V
Python 2.7.13 -- Enthought, Inc. (x86_64)

$ edm list | grep chaco
chaco                               4.7.2-1        enthought/free
```

**Comment by jwiggins** [comment]
```

**Comment by jwiggins** [comment]
This is a great bug report, but there's a small bug: instead of `render_component(gc, self.plot)`, you should write `gc.render_component(self.plot)`.

(also, this might be a bug in enable, not chaco)

**Comment by notmatthancock** [comment]
> there's a small bug

whoops: leftovers from my own debugging

> Indeed: https://github.com/enthought/enable/blob/master/kiva/pdf.py#L622-L628

I wish all bugs lead to a comment so explicit!

**Comment by notmatthancock** [comment]
I'm a bit too green to dive in and sort this out, but performing the `render_component` in a separate process provides a ridiculous work-around for the time-being, e.g.,

    def _save_fired(self):

        # Do save stuff ...
        self.plot.do_layout(force=True)
        gc = PdfPlotGraphicsContext(filename='./plot.pdf')
        gc.render_component(self.plot)
        gc.save()

        print('plot saved!')

**Comment by notmatthancock** [comment]
That's a simple fix and makes sense.

**Comment by jwiggins** [comment]
Moving to enthought/enable#320
