### ISSUE TITLE
Fonttools related tracebacks in Python 3 CI runs

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#448]
The tracebacks can be found on the job https://ci.appveyor.com/project/EnthoughtOSS/chaco-euxdv/builds/25137381/job/hmdrf33ru6tbxxa2

Note that both the 3.5 and 3.6 appveyor CI jobs finished running the tests successfully.

```
appveyor-run.cmd test %runtime% %toolkits%
Running tests in 'chaco-test-3.5-null'
copying file to tempdir: .coveragerc
[EXECUTING] edm run -e chaco-test-3.5-null -- coverage run -m unittest discover -v chaco
Could not covert font to FontEntry for file c:\windows\fonts\ebrima.ttf
Traceback (most recent call last):
  File "c:\users\appveyor\.edm\envs\chaco-test-3.5-null\lib\site-packages\kiva\fonttools\font_manager.py", line 1440, in <module>
    fontManager = pickle_load(_fmcache)
  File "c:\users\appveyor\.edm\envs\chaco-test-3.5-null\lib\site-packages\kiva\fonttools\font_manager.py", line 1050, in pickle_load
    fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\AppData\\Roaming\\Enthought\\kiva\\fontList.cache'
```

_Originally posted by @rahulporuri in https://github.com/enthought/chaco/pull/445#issuecomment-498010206_

**Comment by jvkersch** [comment]
This should probably be backed by an Enable issue.

**Comment by kitchoi** [comment]
Opened: https://github.com/enthought/enable/issues/363

This is probably related: https://github.com/enthought/enable/issues/362

**Comment by rahulporuri** [comment]
closing as the underlying enable issues have been closed which probably fixes this issue as well
