### ISSUE TITLE
Line Plot with 15k points: crash as Qt catches "Exceeded cell block limit" exception

### ISSUE THREAD

**Issue by nicolasap-dm** [enthought/chaco#474]
**Problem Description**
A LinePlot of a big amount (~15 000) of random, definitely non monotonous, 2D data, causes a crash. The same amount of data (or even much more) but with smaller leaps from one point to the next is handled well.

This is printed to the console when the crash happens:
```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::overflow_error'
  what():  Exceeded cell block limit
```

**Reproduction Steps:**

With this class:

```python
from random import randrange

from chaco.api import ArrayPlotData, Plot
from enable.api import Component, ComponentEditor
from traits.api import HasTraits, Enum, Int, Instance
from traitsui.api import View, VGroup, UItem


class Plotter(HasTraits):

    add_type = Enum(["walk", "leap"])
    points = Int(15000)

    _plot = Instance(Component)
    _plot_data = Instance(ArrayPlotData)

    traits_view = View(VGroup(
        UItem("_plot", editor=ComponentEditor()),))

    def __plot_data_default(self):
        if self.add_type == "leap":
            x = [randrange(10) for i in range(self.points)]
            y = [randrange(10) for i in range(self.points)]
        elif self.add_type == "walk":
            x, y = [4.5], [4.5]
            for i in range(self.points - 1):
                x.append(x[i] + randrange(-4, 5) * 0.015)
                y.append(y[i] + randrange(-4, 5) * 0.015)
        return ArrayPlotData(x=x, y=y)

    def __plot_default(self):
        plot = Plot(self._plot_data)
        plot.plot(
            ('x', 'y'), type='line',
            name='Line plot', marker='circle', bgcolor='white'
        )[0]
        plot.range2d.x_range.low_setting = -1
        plot.range2d.y_range.low_setting = -1
        plot.range2d.x_range.high_setting = 10
        plot.range2d.y_range.high_setting = 10
        return plot
```
These work fine ("smooth" line from random walk, 1M points; "jagged" line from random leaps 10k points):
```
Plotter(add_type="walk", points=1_000_000).configure_traits()
Plotter(add_type="leap", points=10_000).configure_traits()
```
This causes a crash ("jagged", 15k points):
```
Plotter(add_type="leap", points=15_000).configure_traits()
```

**OS, Python version:** Linux (Ubuntu 16.04), Python 3.6.0
```
chaco               4.7.2-4  
enable              4.8.0-2  
pyface              6.1.2-1  
pyqt                4.12.1-1 
qt                  4.8.7-10 
traits              5.1.2-1  
traitsui            6.1.2-1  
```

**Comment by rkern** [comment]
For reference, `Exceeded cell block limit` is an Agg exception: https://stackoverflow.com/questions/37470734/matplotlib-giving-error-overflowerror-in-draw-path-exceeded-cell-block-limit

I don't think we expose setting this value like `matplotlib` does.

**Comment by jwiggins** [comment]
In matplotlib, the call into AGG expects an `OverflowError` if this is triggered: https://github.com/matplotlib/matplotlib/blob/0c75f8ff5dd6a6584c4e740839783172eae00aae/lib/matplotlib/backends/backend_agg.py#L153-L164
I think adding the same `try`/`except` to our Kiva backends will at least avoid the crash, but avoiding the limitation is more complicated.

**Comment by jwiggins** [comment]
OK. I've been deep enough in the AGG code recently that I can finally explain what's going on here.

Drawing with AGG:
1. Create a path
2. Convert the path to a polygon. Lines are just "skinny" polygons.
3. Walk the edges of the polygon and draw straight line segments into the rasterizer. Each pixel drawn is recorded in an unstructured collection of "cells".
4. Sort the cells by their Y values into scanlines
5. Sort scanline cells by their X values
6. Walk each scanline and count cell [edge] crossings to determine segments which lie inside polygons and should be filled.
7. Convert the segments into colored pixels in the final rendered scanline.

Note that overlap isn't checked until step 5 or 6, so step 3 can end up touching the same screen pixels multiple times and generating a new cell each time.

Step 3 is limited to 2^22 total cells by default in AGG. This number can be increased but it's quite deep in the backend code and difficult to expose at the Python level. The way to exceed the cell limit is to draw a single polygon (which might just be a stroked line!) with more than 4 million edge pixels. Conversely, the way to avoid hitting this limit is to do what matplotlib does and break up polygons into manageable chunks which don't overwhelm the rasterizer.

**Comment by jwiggins** [comment]
I'm closing this now that it is tracked by enthought/enable#750
