### ISSUE TITLE
Switch to Enthought Sphinx theme for docs

### ISSUE THREAD

**Issue by jvkersch** [enthought/chaco#479]
For uniformity with other ETS projects, docs should be rendered using  the [Enthought Sphinx theme](https://github.com/enthought/enthought-sphinx-theme).

**Comment by corranwebster** [comment]
This is fixed in #462 when it is done.

**Comment by rahulporuri** [comment]
this was done in https://github.com/enthought/chaco/pull/571, extracted from #462 . closing.
