### ISSUE TITLE
Issue with CalendarScaleSystem

### ISSUE THREAD

**Issue by fred4ets** [enthought/chaco#545]
Hi,

I try to plot data from 0 to 3600 seconds, using CalendarScaleSystem to display the curve in time scale (on both axes).

But I don't understand the result displayed: 

- first, it does not begin at 0 s, but at 1 s;
- second, after 55 mn, it does not display 1 h but 2 h.

Here's a CME (from demo/financial/correlations.py) to be explicit.

```
from enable.component_editor import ComponentEditor
from traits.api import HasTraits, Instance
from traitsui.api import Item, View

from chaco.api import ArrayPlotData, Plot, PlotAxis, \
        ScatterInspectorOverlay
from chaco.scales.api import CalendarScaleSystem
from chaco.scales_tick_generator import ScalesTickGenerator

class PlotApp(HasTraits):

    plotdata = Instance(ArrayPlotData)

    returns_plot = Instance(Plot)

    traits_view = View(Item('returns_plot',
                            editor=ComponentEditor(),
                            show_label = False),
                       width=1200, height=700,
                       resizable=True)

    def __init__(self, **kwtraits):
        super(PlotApp, self).__init__(**kwtraits)
        self._create_data()
        self._create_returns_plot()
        return

    def _create_returns_plot(self):
        plot = Plot(self.plotdata)

        plot.x_axis = None
        x_axis = PlotAxis(plot, orientation="bottom",
                          tick_generator=ScalesTickGenerator(scale=CalendarScaleSystem()))
        plot.overlays.append(x_axis)
        plot.x_grid.tick_generator = x_axis.tick_generator
        plot.y_axis = None
        y_axis = PlotAxis(plot, orientation="left",
                          tick_generator=ScalesTickGenerator(scale=CalendarScaleSystem()))
        plot.overlays.append(y_axis)
        plot.y_grid.tick_generator = y_axis.tick_generator

        plot.plot(('x0', 'y0'), type='line')

        self.returns_plot = plot

    def _create_data(self):
        plotdata = ArrayPlotData()
        a = range(3610)
        plotdata.set_data('x0', a)
        plotdata.set_data('y0', a)
        self.plotdata = plotdata


demo = PlotApp()
if __name__ == "__main__":
    demo.configure_traits()
```

What am I doing wrong?

Debian stable 64bits, Python 3.7.3

Traits code source freshly pulled and built (this morning) from git repository

Thanks for your help.

Regards

**Comment by rahulporuri** [comment]
When I run the script locally on a windows machine with python 3.6 environment, I see the following -

![reproduce](https://user-images.githubusercontent.com/1926457/102089407-12c37700-3e14-11eb-8fa3-ce70050146a3.png)

My environment 
- traits==6.1.1
- traitsui==7.1.1
- pyface==7.1.0
- chaco==4.8.0
- enable==4.8.1
- envisage==5.0.0

**Comment by fred4ets** [comment]
OK.

And this is what I get.


Le 14/12/2020 à 14:58, Poruri Sai Rahul a écrit :

**Comment by corranwebster** [comment]
Note that for the calendar scale 0-3600 means the first hour of the Unix Epoch (so midnight 1st Jan 1970 UTC) but displayed using the current timezone.  So that's most likely what's causing the end of the plot being at 2:00 AM (and perhaps the 1 at the start is 1:00 AM not 1 minute?) - that would be right if you are in Western Europe.

If you are in the UK, things are complicated by the fact that the UK was on daylight savings time all year for 1970 (see https://en.wikipedia.org/wiki/British_Summer_Time#Periods_of_deviation); which is correctly taken into account by Mac OS and Linux, but which Windows _doesn't_ IIRC.

**Comment by fred4ets** [comment]
OK.
I'm in Western Europe.

So, how can I display 0 to 1 h by step 5mn on the axis?

**Comment by fred4ets** [comment]
OK.

I can substract 3600 from data on axes.

But in this case, it display "1/01" at axes origin.

But I want origin to be 0, not a date.

PS : in the real life, I want to display time computation on y axis vs parameter on x axis, so date is meaningless.
![snapshot](https://user-images.githubusercontent.com/35263926/102118316-d148c100-3e3f-11eb-976f-4b5454220cec.png)

**Comment by fred4ets** [comment]
OK.

Thanks for the hint.

Regards

**Comment by corranwebster** [comment]
An additional note here - if you don't want the day/month/year information, you can set up a `CalendarScaleSystem` with just hours minutes seconds:
```
from chaco.scales.api import CalendarScaleSystem, HMSScales

hms_scale_system = CalendarScaleSystem(scales=HMSScales)
```
If you don't want hours, you could even use `HMSScales[:-1]`.  I think this might give you the output you want if you are using less than an hour of data.

**Comment by fred4ets** [comment]
Ok, nice!

Thanks again :)

**Comment by fred4ets** [comment]
Hi, 

I have tried your hint, Corran, but I still have the date "1/01" displayed.

![snapshot](https://user-images.githubusercontent.com/35263926/102977701-a7f4f880-4503-11eb-8afc-d24cb3a5c16b.png)

`from numpy import arange

from enable.component_editor import ComponentEditor
from traits.api import HasTraits, Instance
from traitsui.api import Item, View

from chaco.api import ArrayPlotData, Plot, PlotAxis, \
        ScatterInspectorOverlay
from chaco.scales.api import CalendarScaleSystem
from chaco.scales.time_scale import HMSScales
from chaco.scales_tick_generator import ScalesTickGenerator

class PlotApp(HasTraits):

    plotdata = Instance(ArrayPlotData)

    returns_plot = Instance(Plot)

    traits_view = View(Item('returns_plot',
                            editor=ComponentEditor(),
                            show_label = False),
                       width=1200, height=700,
                       resizable=True)

    def __init__(self, **kwtraits):
        super(PlotApp, self).__init__(**kwtraits)
        self._create_data()
        self._create_returns_plot()
        return

    def _create_returns_plot(self):
        plot = Plot(self.plotdata)

        plot.x_axis = None
        x_axis = PlotAxis(plot, orientation="bottom",
                          tick_generator=ScalesTickGenerator(scale=CalendarScaleSystem(scales=HMSScales)))
        plot.overlays.append(x_axis)
        plot.x_grid.tick_generator = x_axis.tick_generator
        plot.y_axis = None
        y_axis = PlotAxis(plot, orientation="left",
                          tick_generator=ScalesTickGenerator(scale=CalendarScaleSystem(scales=HMSScales)))
        plot.overlays.append(y_axis)
        plot.y_grid.tick_generator = y_axis.tick_generator

        plot.plot(('x0', 'y0'), type='line')

        self.returns_plot = plot

    def _create_data(self):
        plotdata = ArrayPlotData()
        a = arange(3610)-3600
        plotdata.set_data('x0', a)
        plotdata.set_data('y0', a)
        self.plotdata = plotdata


demo = PlotApp()
if __name__ == "__main__":
    demo.configure_traits()
`

Do I am missing something?

**Comment by corranwebster** [comment]
No - I didn't test it myself, but what you wrote is something like I had in mind.  What you are seeing feels like a bug - if you specify HMS only, then it shouldn't generate ticks for days months or years.

I'll have another look at the code - it could be something in the label generation.

**Comment by corranwebster** [comment]
OK, it _is_ the formatter that is causing this, and so the fix is somewhat harder, because the formatters appear to be hard to override.  You'll need something like (warning: untested code):
```
my_formatter = TimeFormatter(
    _formats = {
        'microseconds': ('%(us)us', '%(ms_).%(us)ms'),
        'milliseconds': ('%(ms)ms', '%S.%(ms)s'),
        'seconds': (':%S', '%Ss'),
        'minsec': ('%M:%S',),
        'minutes': ('%Mm',),
        'hourmin': ('%H:%M',),
        'hours': ('%Hh', '%H:%M'),
        'days': ('%Hh', '%H:%M'), # override default
        'months': ('%Hh', '%H:%M'), # override default
        'years': ('%Hh', '%H:%M'), # override default
    }
)
my_HMSScales = [
    TimeScale(microseconds=1, formatter=my_formatter),
    TimeScale(milliseconds=1, formatter=my_formatter)
] + [
    TimeScale(seconds=dt, formatter=my_formatter)
    for dt in (1, 5, 15, 30)
] +[
    TimeScale(minutes=dt, formatter=my_formatter)
    for dt in (1, 5, 15, 30)
] + [
    TimeScale(hours=dt, , formatter=my_formatter)
    for dt in (1, 2, 3, 4, 6, 12, 24)
]
```
and then use `my_HMSScales` as in your example.  It may be simpler to just create your own formatter class that does exactly what you want.

This is way harder than it ought to be, and so I am going to open an issue for this.

**Comment by fred4ets** [comment]
OK.

I have tested it, and it gives the same result.

But anyway, thanks a lot for your help.
