### ISSUE TITLE
Y label gets clipped

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#564]
**Problem Description**

The Y label in the following example doesn't get displayed while the X label gets displayed.

![why-chaco-why](https://user-images.githubusercontent.com/1926457/107530112-73bcc080-6bb3-11eb-920b-d4beaf1ae329.png)

**Reproduction Steps:**

```python
from numpy import linspace, sin
from traits.api import HasTraits, Instance
from traitsui.api import View, Item
from chaco.api import Plot, ArrayPlotData
from enable.api import ComponentEditor

class LinePlot(HasTraits):
    plot = Instance(Plot)

    traits_view = View(
        Item('plot',editor=ComponentEditor(), show_label=False),
        width=500, height=500, resizable=True, title="Chaco Plot")

    def _plot_default(self):
        x = linspace(-14, 14, 100)
        y = sin(x) * x**3
        plotdata = ArrayPlotData(x=x, y=y)

        plot = Plot(plotdata)
        plot.plot(("x", "y"), type="line", color="blue")
        plot.title = "sin(x) * x^3"
       
        plot.x_axis.title = "X AXIS"
        plot.y_axis.title = "Y AXIS"
       
        return plot

if __name__ == "__main__":
    LinePlot().configure_traits()
```

**Expected behavior:**

We expect the Y label to be displayed.

**OS, Python version:** Windows 10 Pro. Python 3.6.0. Chaco 4.8.0. Enable 4.8.1.

Originally reported on the ETS Users Google Group - https://groups.google.com/g/ets-users/c/gHQmFsVMVhw

**Comment by timdiller** [comment]
Note that the title is actually there, but the default padding is such that most of the text is clipped.  This requires overriding the `plot.padding_left` attribute to create enough space to show the text.

**Comment by corranwebster** [comment]
This is not a bug per-se as @timdiller points out - but what might help with these problems is to perhaps adjust the _default_ values of the right and left padding based on the presence or absence of a non-empty axis title.

Or alternatively, use the edge of the padding as the guide for the location of the axis title?
