### ISSUE TITLE
API documentation refactor

### ISSUE THREAD

**Issue by aaronayres35** [enthought/chaco#586]
**Problem Description**
(Assuming #462 is merged)
API documentation needs a refactor.
Currently there exist various forms of api documentation which are redundant.  In the user guide there is the "Commonly Used Modules and Classes" page which gives information comparable to autogenerated API docs as well as some additional clarifying text.  Additionally, the following more specific sections will sometimes contain api style docs for that particular topic of interest, e.g giving the api details of the AbstractMapper interface.
Finally there is the full autogenerated API reference itself.  

It may be reasonable to leave some of this repetition, however how we want to go about this should be more well thought out.

**Comment by rahulporuri** [comment]
closing as we addressed this over a number of PRs
