### ISSUE TITLE
kiva/fonttools/font_manager.py createFontList(fontfiles, fontext) missing catch for TTLibError

### ISSUE THREAD

**Issue by GaryHendrick** [enthought/chaco#60]
The try block found in kiva/fonttools/font_manager.py createFontList(fontfiles, fontext)

``` Python
684             try:
--> 685                 font = TTFont(str(fpath))
686             except...
```

Should include an except clause for TTLibError raised in  kiva/fonttools/fontTools/ttLib/sfnt.pyc in **init**(self, file, checkChecksums)

``` Python
     35                 if self.sfntVersion not in ("\000\001\000\000", "OTTO", "true"):
     36                         from kiva.fonttools.fontTools import ttLib
---> 37                         raise ttLib.TTLibError, "Not a TrueType or OpenType font (bad sfntVersion)"
     38                 self.tables = {}
     39                 for i in range(self.numTables):
```

Resulting in the bubbling up of

``` Python
TTLibError: Not a TrueType or OpenType font (bad sfntVersion)
```

Lacking this except, a TTLibError will cause a failure in the font manager. This issue was discovered when attempting to import ChacoPlotItem using

``` Python
from enthought.chaco.chaco_plot_editor import ChacoPlotItem
```

Best Regards,
Gary

**Comment by rahulporuri** [comment]
closing this ticket as there isnt any update regarding the original issue and this issue seems to have been fixed in newer enable.
