### ISSUE TITLE
changing Plot's legend

### ISSUE THREAD

**Issue by fred4ets** [enthought/chaco#635]
Hi,

I would like to change the legend of a line plot for instance.

If I understand correctly, legend is automatically deduced from string in plot.plots.

But I would like to set the legend to another string.

Here's the CME:

```python
# Major library imports
from numpy import arange
from scipy.special import jn

# Enthought library imports
from enable.api import Component, ComponentEditor
from traits.api import HasTraits, Instance
from traitsui.api import Item, Group, View

# Chaco imports
from chaco.api import (
    create_line_plot,
    add_default_axes,
    add_default_grids,
    OverlayPlotContainer,
    Legend, Label
)
from chaco.tools.api import PanTool, ZoomTool, LegendTool, TraitsTool, DragZoom
from chaco.example_support import COLOR_PALETTE


class PlotContainer(OverlayPlotContainer):
    """Simple container for creating a series of plots"""

    def __init__(self, *args, **kws):
        super(OverlayPlotContainer, self).__init__(*args, **kws)
        self._setup_plots()

    def _setup_plots(self):
        """Creates series of Bessel function plots"""
        plots = {}
        x = arange(1, 10, 0.01)
        y = jn(0, x)
        plot = create_line_plot((x, y))

        value_mapper, index_mapper, legend = self._setup_plot_tools(plot)
        self.add(plot)
        plots["Bessel j_0"] = plot

        # Set the list of plots on the legend
        legend.plots = plots

    def _setup_plot_tools(self, plot):
        """Sets up the background, and several tools on a plot"""
        # Make a white background with grids and axes
        plot.bgcolor = "white"
        add_default_grids(plot)
        add_default_axes(plot)

        # Add a legend in the upper right corner, and make it relocatable
        legend = Legend(component=plot, padding=10, align="ur")
        label = Label(text='foo')
        legend.labels = [label]
        legend.tools.append(LegendTool(legend, drag_button="right"))
        plot.overlays.append(legend)
        return plot.value_mapper, plot.index_mapper, legend

size = (800, 700)
title = "Simple Line Plot"


class PlotExample(HasTraits):
    plot = Instance(Component)

    traits_view = View(
        Group(
            Item("plot", editor=ComponentEditor(size=size), show_label=False),
            orientation="vertical",
        ),
        resizable=True,
        title=title,
        width=size[0],
        height=size[1],
    )

    def _plot_default(self):
        return PlotContainer(
            padding=50,
            fill_padding=True,
            bgcolor="lightgray",
            use_backbuffer=True,
        )


demo = PlotExample()


if __name__ == "__main__":
    demo.configure_traits()
```

Line 52, I set
  label = Label(text='foo')
and just below,
legend.labels = [label]

But instead of displaying "foo" in the legend, a blank legend is displayed.
![snapshot](https://user-images.githubusercontent.com/35263926/114026954-2be6ac80-9877-11eb-8291-71cfe5cf8a88.png)
 
What am I doing wrong?

How could I get what I want ("foo" displayed in legend)?

Thanks in advance

Regards

**Debian 10 x86_64, Pyhton 3.7, ETS source from git source**

**Comment by aaronayres35** [comment]
Looking into this, this is the relevant code:
https://github.com/enthought/chaco/blob/4b4b6480c95c40c00345e748e9d9f98f3627cf0d/chaco/legend.py#L378-L399

It appears that `labels` is meant to only contain keys from the `plots` dict.  ie for control over which plots have a label shown in the legend, but not for the text of the labels used to display them.
Is there a specific reason you want the key in the `legend.plots` dict to not match the text in the legend? By changing your line `plots["Bessel j_0"] = plot` to `plots["foo"] = plot` and removing `label = Label(text='foo')`/ `legend.labels = [label]` the legend displays "foo" as desired.

Looking at the source code for the `Legend` class it appears that the keys of `legend.plots` are exclusively used for the labels to display in the legend and nothing else.


The `Plot` class also has a `plots` dict trait, but I don't believe that is used here.  Here you have an `OverlayPlotContainer` and are populating it with a `LinePlot` (created by `create_line_plot`).  `LinePlot` is actually a subclass of `AbstractPlotRenderer` not `Plot`.  I apologize if my answer is causing confusion, the naming of things can be a bit complicated.

Nonetheless, in this case the `plots` dict you have defined in `_setup_plots` is _only_ used by the legend, and the keys are even further _only_ used to specify the text to be shown in the legend.

I hope this helps!

**Comment by fred4ets** [comment]
Hi,

This is too long to explain why I want to set labels independently of plots's keys, because I develop my GUI for too many years.

Anyway, I followed your advice, I had to found a workaround, and I get it.

Thanks for your help.
