### ISSUE TITLE
Consolidate plots into a new "chaco.plots"?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#700]
- [`BarPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/barplot.py#L41)
- [`CandlePlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/candle_plot.py#L26)
- [`CMapImagePlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/cmap_image_plot.py#L20)
- [`ColorBar`](https://github.com/enthought/chaco/blob/1ed123cc65d4fd2b9a53a238cd584f8c5dfcac68/chaco/color_bar.py#L28)
- [`ColormappedSegmentPlot`](https://github.com/enthought/chaco/blob/1ed123cc65d4fd2b9a53a238cd584f8c5dfcac68/chaco/segment_plot.py#L434)
- [`ColorMappedScatterPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/colormapped_scatterplot.py#L46)
- [`QuiverPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/quiverplot.py#L12)
- [`ContourLinePlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/contour_line_plot.py#L17)
- [`ContourPolyPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/contour_poly_plot.py#L16)
- [`ErrorBarPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/errorbar_plot.py#L16)
- [`FilledLinePlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/filled_line_plot.py#L16)
- [`HorizonPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/horizon_plot.py#L28)
- [`ImagePlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/image_plot.py#L54)
- [`JitterPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/jitterplot.py#L11)
- [`LinePlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/lineplot.py#L35)
- [`LineScatterPlot1D`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/line_scatterplot_1d.py#L17)
- [`MultiLinePlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/multi_line_plot.py#L34)
- [`PolarLineRenderer`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/polar_line_renderer.py#L16)
- [`PolygonPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/polygon_plot.py#L17)
- [`ScatterPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/scatterplot.py#L198)
- [`ScatterPlot1D`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/scatterplot_1d.py#L17)
- [`SegmentPlot`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/segment_plot.py#L24)
- [`TextPlot`](https://github.com/enthought/chaco/blob/1ed123cc65d4fd2b9a53a238cd584f8c5dfcac68/chaco/text_plot.py#L20)
- [`TextPlot1D`](https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/text_plot_1d.py#L20)

and the respective baseclasses. Ref https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/docs/source/user_manual/modules_and_classes.rst#renderers

**Comment by corranwebster** [comment]
I'd suggest leaving the `Abstract` classes where they are.

**Comment by aaronayres35** [comment]
I did github searches for imports directly from these modules as opposed to importing from chaco.api 

I saw users importing directly from `chaco.color_bar`, `chaco.colormapped_scatterplot`, `chaco.horizon_plot`, `chaco.line_plot`, `chaco.multi_line_plot`, and `chaco.scatterplot`.
