### ISSUE TITLE
Downstream users still import marker_trait from chaco.api

### ISSUE THREAD

**Issue by aaronayres35** [enthought/chaco#771]
This was removed in PR #679

To avoid breaking code we should bring it back into the `chaco.api` for the 5.0.0 release

**Comment by thomas-bersano** [comment]
I would like to note that the first example of a dynamically changing plot in the tutorial on enthought.com relies on marker_trait from chaco.api and therefore can not be run in the current version of chaco.

**Comment by gapster** [comment]
The tutorial on enthought.com is broken because **_you created a backward incompatibility_**. (Really?  Who does that.)  Please fix the incompatibility, or at least **_fix the tutorial_**
