### ISSUE TITLE
ImportError: cannot import name 'marker_trait' from 'chaco.api'

### ISSUE THREAD

**Issue by homosapien-lcy** [enthought/chaco#866]
**Problem Description**
ImportError: cannot import name 'marker_trait' from 'chaco.api' when trying to run a 2008 demo

**Reproduction Steps:**

```python
python chaco/examples/tutorials/scipy2008/traits_example.py
```

**Expected behavior:**
test past

**OS, Python version:** [MacOS, python3.8 (with or without edm) or 3.11]

**Comment by homosapien-lcy** [comment]
It seems that BaseTool should be imported from the enable api https://github.com/enthought/enable/blob/main/enable/api.py (line 272), we probably can solve this by importing BaseTool in chaco.api (from enable.api)

**Comment by corranwebster** [comment]
In general it is better to fix the demo to conform to the current API than changing the API.  Import from enable in the example if that is where things currently are.
